name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: install newman
      run: npm install -g newman
    
    - name: install newman-reporter-htmlextra
      run: npm install -g newman-reporter-htmlextra

    - name: Build
      run: npm run build --if-present

    - name: Deploy
      run: echo "Deploying to your server..."

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r playwright/requirements.txt

    - name: Run Python script
      run: playwright install

    - name: pytest the script
      run: pytest playwright/run_test.py --html=UI_report.html --self-contained-html

    - name: API test
      run: newman run test.postman_collection.json -r \
          htmlextra --reporter-html-export html_report.html

    - name: Upload UI test report
      uses: actions/upload-artifact@v2
      with:
        name: UI-test-report
        path: UI_report.html
    
    - name: Upload API test report
      uses: actions/upload-artifact@v2
      with:
        name: API-test-report
        path: API_report.html
