name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present

    - name: Deploy
      run: echo "Deploying to your server..."

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r playwright/requirements.txt

    - name: Install missing libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libwoff1 libvpx6 libevent-2.1-6 libopus0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libharfbuzz-icu0 libhyphen0 libmanette-0.2-0 libflite1 libgles2 libx264-155

    - name: Run Python script
      run: playwright install

    - name: pytest the script
      run: pytest playwright/run_test.py
