name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test

    - name: Build
      run: npm run build --if-present

    - name: Deploy
      run: echo "Deploying to your server..."
